# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13J4fOLbZSN1jVhcA0dniWmkGYi6jo4Yx
"""



pandas
streamlit
seaborn
numpy







